// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQSy94iWgesUDfCNvlDtgGDoAPOU8R7Q',
    appId: '1:894359798138:web:267ed666fb9496816496c3',
    messagingSenderId: '894359798138',
    projectId: 'combinacion1-0',
    authDomain: 'combinacion1-0.firebaseapp.com',
    storageBucket: 'combinacion1-0.appspot.com',
    measurementId: 'G-91W5080DHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxql-g1BxTcQRMDGmyqOdaPaK0VRCUlKg',
    appId: '1:894359798138:android:cf3bf4af9725de6a6496c3',
    messagingSenderId: '894359798138',
    projectId: 'combinacion1-0',
    storageBucket: 'combinacion1-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8tYueqm47EyBMtP_kX2_bjooLliRzsQ',
    appId: '1:894359798138:ios:44dfbe5a89ce46c76496c3',
    messagingSenderId: '894359798138',
    projectId: 'combinacion1-0',
    storageBucket: 'combinacion1-0.appspot.com',
    iosClientId: '894359798138-ouhpdhap1oc6nn3q6v38qsfm4seud2bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.combinacion10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX8tYueqm47EyBMtP_kX2_bjooLliRzsQ',
    appId: '1:894359798138:ios:44dfbe5a89ce46c76496c3',
    messagingSenderId: '894359798138',
    projectId: 'combinacion1-0',
    storageBucket: 'combinacion1-0.appspot.com',
    iosClientId: '894359798138-ouhpdhap1oc6nn3q6v38qsfm4seud2bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.combinacion10',
  );
}
